ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
    watch:
      - backend
  application:
    modules:
      - cloud.angora.ApplicationKt.module

database:
  url: "${DB_URL:jdbc:postgresql://localhost:5432/angora}"
  user: "${DB_USER:angora}"
  password: "${DB_PASSWORD:angora}"
